### ISSUE TITLE
Script to rename file for bongo

### ISSUE THREAD

**Issue by zobi8225** [dbrock/bongo#13]
Hi, i love bongo,
Do you know if a script witch can automaticly rename all fime from a library exist.
Thx

**Comment by zobi8225** [comment]
Sorry, i post too quick

**Comment by dbrock** [comment]
I guess you found the old `tree-from-tags.rb` script. :smile:

Did you get it to work?

**Comment by dbrock** [comment]
Ah, I guess not, due to #5?

**Comment by zobi8225** [comment]
Yes i fond the script, but it don't work on my archlinux (64) beaccause the ruby's taglib dont work :-(
https://aur.archlinux.org/packages/ruby-taglib/
