### ISSUE TITLE
Bongo not on MELPA?

### ISSUE THREAD

**Issue by ReneFroger** [dbrock/bongo#26]
Hi Lit, thanks for sharing this package! It's appreciated.

However, I couldn't find it on MELPA. Could this perhaps be listed on MELPA?

Thanks in advance!

**Comment by manuel-uberti** [comment]
It's [here](http://melpa.org/#/bongo), or am I missing something?

**Comment by ReneFroger** [comment]
Sorry. Seems I didn't have refreshed the contents of package.el
