### ISSUE TITLE
Are there anybody who enjoys how bongo destroys current window configuration?

### ISSUE THREAD

**Issue by Bad-ptr** [dbrock/bongo#38]
See the [`bongo-quit`](https://github.com/dbrock/bongo/blob/master/bongo.el#L10545), and [`bongo`](https://github.com/dbrock/bongo/blob/master/bongo.el#L10606) functions.
Can you make saving/setting window configuration optional?

I think that the logic of this behavior is broken because after you call `bongo-quit`(which deletes other windows which is terrible) you can split/delete windows and then `bongo` revives what you don't need anymore(window configuration from the past). This is confusing.

**Comment by iqbalansari** [comment]
I agree, the way `bongo` interacts with the window configuration is broken right now, maybe we should remove that part, since nowadays there are better tools to manage window configurations (like `winner-mode`).

**Comment by dbrock** [comment]
You're right, this probably does more harm than good.

Personally, I very seldom use more than two windows, so I guess I wouldn't really have noticed this...
