### ISSUE TITLE
tree-from-tags.rb depends on ruby-taglib which only works with deprecated ruby 1.8.

### ISSUE THREAD

**Issue by graaff** [dbrock/bongo#5]
The ruby-taglib code that tree-from-tags.rb depends on only works with ruby 1.8 and not with newer versions. ruby 1.8 has been deprecated for some time already, and final security support has stopped this summer.

https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/

tree-from-tags.rb should probably be ported to a newer, maintained, version ruby taglib bindings. taglib-ruby looks like a good, maintained, candidate: http://robinst.github.io/taglib-ruby/

**Comment by iqbalansari** [comment]
@dbrock I think this can be closed as well
